name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Deploy to Nginx server via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: 127.0.0.1/pipeline
        SSH_USERNAME: ayaz
        REMOTE_DIR: /home/ayaz/Desktop/react-cicd/build
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r build/* ${SSH_USERNAME}@${SSH_HOST}:${REMOTE_DIR}
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          sudo systemctl restart nginx
